apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ko961jppp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ko961jppp-go 
  name: ko961jppp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ko961jppp-go 
